AWSTemplateFormatVersion: '2010-09-09'
Description: 'HCS ISILON internal security group for OneFS Cluster'
Parameters:
  pVpcId:
    Description: VPC Id
    Type: AWS::EC2::VPC::Id

Resources:
  rISILONInternalSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref pVpcId
      GroupName: 'HCS-ISILON-CLUWE-Internal-SG'
      GroupDescription: "CLUWE ISILON Internal Security Group for OneFS Cluster"
      Tags:
        - Key: 'Isilon-cluster-name'
          Value: 'statsclstr4'
      SecurityGroupIngress:
          IpProtocol: '-1'
      SecurityGroupEgress:
          IpProtocol: '-1'
     
