AWSTemplateFormatVersion: '2010-09-09'
Description: 'HCS ISILON placement group for OneFS cluster'

Resources:
  rISILONPlacementGroup:
    Type: 'AWS::EC2::PlacementGroup'
    Properties:
      Strategy: 'spread'
      GroupName: 'vonefs-cfv-onefs-placement-group'
      Tags:
        - Key: 'Isilon-cluster-name'
          Value: 'vonefs-cfv'
